// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBk__Wl9kdGQ5kD2_9qRnOrwkcP6vsiIk',
    appId: '1:701178304158:web:72c2fde946b334317c0d8f',
    messagingSenderId: '701178304158',
    projectId: 'v-d-o-player',
    authDomain: 'v-d-o-player.firebaseapp.com',
    databaseURL: 'https://v-d-o-player-default-rtdb.firebaseio.com',
    storageBucket: 'v-d-o-player.appspot.com',
    measurementId: 'G-9XNPPKB616',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsAqJhU6Uw9eNl6K16xBbH6Aa1bT-SqQc',
    appId: '1:701178304158:android:c2658534c30af86d7c0d8f',
    messagingSenderId: '701178304158',
    projectId: 'v-d-o-player',
    databaseURL: 'https://v-d-o-player-default-rtdb.firebaseio.com',
    storageBucket: 'v-d-o-player.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUkYZxWchWzuuCEa1Q1L2z-gYO1gEF7k',
    appId: '1:701178304158:ios:d2b23fbf83f821147c0d8f',
    messagingSenderId: '701178304158',
    projectId: 'v-d-o-player',
    databaseURL: 'https://v-d-o-player-default-rtdb.firebaseio.com',
    storageBucket: 'v-d-o-player.appspot.com',
    androidClientId: '701178304158-84dal5fioh7li9ksi8bs0d8g81lrf88p.apps.googleusercontent.com',
    iosClientId: '701178304158-vuig6psrqgt76nfliqtfdgq2aadbvjqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHUkYZxWchWzuuCEa1Q1L2z-gYO1gEF7k',
    appId: '1:701178304158:ios:d2b23fbf83f821147c0d8f',
    messagingSenderId: '701178304158',
    projectId: 'v-d-o-player',
    databaseURL: 'https://v-d-o-player-default-rtdb.firebaseio.com',
    storageBucket: 'v-d-o-player.appspot.com',
    androidClientId: '701178304158-84dal5fioh7li9ksi8bs0d8g81lrf88p.apps.googleusercontent.com',
    iosClientId: '701178304158-vuig6psrqgt76nfliqtfdgq2aadbvjqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vdo',
  );
}
